[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[prune]
  go-tests = true
  unused-packages = true
